# Generated by Django 4.0.6 on 2022-08-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=799012, editable=False, unique=True, verbose_name='Unique ID'),
        ),
    ]
