# Generated by Django 4.0.6 on 2022-08-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0002_alter_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=692765, editable=False, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
